### ISSUE TITLE
Unpined tab goes to Pined tabs row when tab is selected(activated)

### ISSUE THREAD

**Issue by xxxxxxbox** [Dylan700/LeastRecentlyUsedTabsExtension#7]
Great Idea of Plugin, but I can't use it at all due to misbehavior.

There two types of tabs In VScode - Pinned and Unpinned.
Pinned tabs are placed on one row. Unpinned - on another row.

With this pligin unpined tab goes to Pined tabs row when tab is selected(activated).
I'dont want to mix different types of tabs, so can't use plugin until fixed.

![pinned](https://github.com/Dylan700/LeastRecentlyUsedTabsExtension/assets/56993366/91c99fdc-f3e6-4dc1-8822-0e3a8cc9695c)

**Comment by Dylan700** [comment]
Hi @xxxxxxbox thanks for bringing this to my attention. I don't use pinned tabs myself so this behaviour has escaped my knowledge! 

If you would like to contribute, you are welcome to make a pull request with your changes. Otherwise, I'll fix this up for you (hopefully in the next few weeks) and let you know.

**Comment by xxxxxxbox** [comment]
> If you would like to contribute, you are welcome to make a pull request with your changes
@ Dylan700 thanx for reply. I cant contribute to your project as I've no experiance working with VS Code API and TypeScript is not in my skills.

**Comment by Dylan700** [comment]
> @Dylan700 thanx for reply. I cant contribute to your project as I've no experiance working with VS Code API and TypeScript is not in my skills.
> > If you would like to contribute, you are welcome to make a pull request with your changes
> 
> 

No worries at all, I'll look at implementing this in the near future then!

**Comment by Dylan700** [comment]
This issue is caused by the onDidChangeActiveTextEditor method being fired twice. I've begun working on a fix but this will likely take some time given my availability. This also looks like it was an existing bug as per https://github.com/microsoft/vscode/issues/38818
